force-app/main/default/objects/Serial__c/Serial__c.object-meta.xml
<CustomObject>
    <label>Serial</label>
    <nameField>
        <label>Series Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Serial__c/fields/Opis_serialu__c.field-meta.xml
<CustomField>
    <fullName>Opis_serialu__c</fullName>
    <label>Series description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CreateSerialForUsersControllerTest.cls
@isTest
public with sharing class CreateSerialForUsersControllerTest {
    @isTest
    public static void justOneSeries() {
        Id serId;
        Serial__c ser = new Serial__c(Name = 'test', Opis_serialu__c = 'Dłuuuuuuugi Opissssssssssssss Serialuuuuuuuuuuu' );
        try{
            serId = CreateSerialForUsersController.insertSerial(ser);
        }catch(Exception er){
            System.debug(er.getStackTraceString());
        }
        System.debug(serId);
        System.assert(serId != null);

    }
    @isTest
    public static void twoOfTheSameSeries(){
        Id serId;
        Serial__c ser = new Serial__c(Name = 'test', Opis_serialu__c = 'Dłuuuuuuugi Opissssssssssssss Serialuuuuuuuuuuu' );
        try{
            CreateSerialForUsersController.insertSerial(ser);
        }catch(Exception er){
            System.debug(er.getStackTraceString());
        }
        Serial__c ser2 = new Serial__c(Name = 'test', Opis_serialu__c = 'Dłuuuuuuugi Opissssssssssssss Serialuuuuuuuuuuu2' );
        try{
            serId = CreateSerialForUsersController.insertSerial(ser2);
        }catch(Exception er){
            System.debug(er.getStackTraceString());
        }
        System.debug(serId);
        System.assert(serId == null);
    }
}