force-app/main/default/objects/Actor__c/Actor__c.object-meta.xml
<CustomObject>
    <label>Actor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActorSerialAssociation__c/ActorSerialAssociation__c.object-meta.xml
<CustomObject>
    <label>ActorSerialAssociation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ActorSerialAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ActorSerialAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ActorSerialAssociation__c/fields/Actor__c.field-meta.xml
<CustomField>
    <fullName>Actor__c</fullName>
    <label>Actor</label>
    <referenceTo>Actor__c</referenceTo>
    <relationshipLabel>ActorSerialAssociations</relationshipLabel>
    <relationshipName>ActorSerialAssociations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ActorSerialAssociation__c/fields/Serial__c.field-meta.xml
<CustomField>
    <fullName>Serial__c</fullName>
    <label>Serial</label>
    <referenceTo>Serial__c</referenceTo>
    <relationshipLabel>ActorSerialAssociations</relationshipLabel>
    <relationshipName>ActorSerialAssociations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Episode__c/Episode__c.object-meta.xml
<CustomObject>
    <label>Episode</label>
    <nameField>
        <label>Tytuł odcinka</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Episodes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Episode__c/fields/Episode_details__c.field-meta.xml
<CustomField>
    <fullName>Episode_details__c</fullName>
    <description>Syopsis of evenets hapening in this episode</description>
    <label>Episode details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Episode__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Episodes</relationshipLabel>
    <relationshipName>Episodes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Nazwa Sezonu</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Season__c/fields/Serial__c.field-meta.xml
<CustomField>
    <fullName>Serial__c</fullName>
    <label>Serial</label>
    <referenceTo>Serial__c</referenceTo>
    <relationshipLabel>Seasons</relationshipLabel>
    <relationshipName>Seasons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Serial__c/Serial__c.object-meta.xml
<CustomObject>
    <label>Serial</label>
    <nameField>
        <label>Series Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Serial__c/fields/Opis_serialu__c.field-meta.xml
<CustomField>
    <fullName>Opis_serialu__c</fullName>
    <label>Series description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Serial__c/fields/Url_for_logo__c.field-meta.xml
<CustomField>
    <fullName>Url_for_logo__c</fullName>
    <label>Url for logo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Serial__c/fields/Url_to_trailer__c.field-meta.xml
<CustomField>
    <fullName>Url_to_trailer__c</fullName>
    <label>Url to trailer on YT</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/SerialeController.cls
public with sharing class SerialeController {
    @AuraEnabled
    public static List<Episode__c> queryEpisodesWithSerial(Id serialId) {
        return [SELECT Name, Id FROM Episode__c WHERE Season__c IN (SELECT Id FROM Season__c WHERE Serial__c = :serialId) ];
    }
    @AuraEnabled
    public static Serial__c querySeriesWithId(Id recordId) {
        return [SELECT Name, Opis_serialu__c, Url_for_logo__c, Url_to_trailer__c
        FROM Serial__c WHERE Id = :recordId LIMIT 1];
    }
    @AuraEnabled
    public static List<Season__c> querySeasonsWithSerial(Id SerialId){
       return [SELECT Name, Id FROM Season__c WHERE Serial__c = :SerialId];
    }
    @AuraEnabled
    public static Id insertEpisode(Episode__c epi){
        List <Episode__c> epiList = [SELECT Id, Name FROM Episode__c WHERE Name = :epi.Name];
        if(epiList.size()<1 && epi.Name.length() > 1){
            try{
                insert epi;
            }catch(Exception ex) {
                System.debug(ex);
            }
            
        }
        return epi.Id;
    }
    @AuraEnabled
    public static List<Actor__c> queryActorsFromSerial(Id serialId){
        // if(!isAllowedIdType(serialId, Serial__c)){
        //     return null;
        // }
        return [SELECT Name, Id FROM Actor__c WHERE Id IN (SELECT Actor__c FROM ActorSerialAssociation__c
        WHERE Serial__c = :serialId)]; 
    }
    @AuraEnabled
    public static List<Episode__c> queryEpisodesFromSeason(Id seasonId){
    //    if(!isAllowedIdType(seasonId, Season__c)){
    //     return null;
    //    }
       return [SELECT Name, Id, Episode_details__c FROM Episode__c WHERE Season__c = :seasonId];
    }
    public static Boolean isAllowedIdType( String inputId, String objectType )
{
    if ( !String.isBlank( inputId ) && inputId instanceof Id )
    {
        Id verifyId = Id.valueOf( inputId );
        if ( objectType.equalsIgnoreCase( verifyId.getSobjectType( ).getDescribe( ).getName( ) ) )
        {
            return true;
        }
    }
    return false;
    }
}