force-app/main/default/objects/Episode__c/Episode__c.object-meta.xml
<CustomObject>
    <label>Episode</label>
    <nameField>
        <label>Tytuł odcinka</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Episodes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Episode__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Episodes</relationshipLabel>
    <relationshipName>Episodes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Nazwa Sezonu</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateBoldAndBeatifullTest.cls
@isTest
public with sharing class CreateBoldAndBeatifullTest {
    @isTest
    public static void CreateBoldAndBeatifullTest() {
        Test.startTest();
        CreateBoldAndBeatifullSeries cBABS = new CreateBoldAndBeatifullSeries(100);
        Id jobId = Database.executeBatch(cBABS, 200);
        Test.stopTest();
        System.assertEquals(99, [SELECT COUNT() FROM Episode__c WHERE Season__c = 'a037Q000001XOrc']);
    }
}