force-app/main/default/objects/Episode__c/Episode__c.object-meta.xml
<CustomObject>
    <label>Episode</label>
    <nameField>
        <label>Tytuł odcinka</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Episodes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Episode__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Episodes</relationshipLabel>
    <relationshipName>Episodes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Nazwa Sezonu</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateBoldAndBeatifullSeries.cls
global with sharing class CreateBoldAndBeatifullSeries implements Database.Batchable<Episode__c>, Database.Stateful{
    private Integer intParameter;

    public CreateBoldAndBeatifullSeries(Integer intParam) {
        intParameter = intParam;
    }
    global Iterable<Episode__c> start(Database.BatchableContext BC){
        return new EpisodeIterable(intParameter);
    }
    global void execute(Database.BatchableContext BC, List<Episode__c> scope){
        List<Episode__c> epsToInsert = new List<Episode__c>();
        
        System.debug('dodałem sezon');
        for(Episode__c ep : scope){
            ep.Season__c = 'a037Q000001XOrc';
            epsToInsert.add(ep);
        }
        insert epsToInsert;
        if(!Test.isRunningTest()){
            System.AbortJob(BC.getJobId());
        }

    }
    global void finish(Database.BatchableContext BC){
        
    }
}